version: "3"
services:
  grafana-dev:
    image: grafana:latest
    container_name: grafana
    restart: always
    networks:
      - grafana
    volumes:
      - ~/Users/felix/Documents/plugins:/var/lib/grafana/plugins
      - grafana-storage-dev:/var/lib/grafana
    ports:
      - 8080:8080
    environment:
      - GF_APP_MODE=development
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=0.1s
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=esnet-arcdiagram-panel
      - GF_LIVE_ALLOWED_ORIGINS=*
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_DEFAULT_THEME=dark

volumes:
  grafana-storage-dev:

networks:
  grafana:
    external: true
    name: grafana